---
title: "EIX"
date: "`r format(Sys.time(), '%d-%m-%Y')`"
output:
  html_document:
    toc: true
    toc_float: true
---
  
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```



Load [`titanic_imputed`](https://modeloriented.github.io/DALEX/reference/titanic.html) data set.

```{r}
data(titanic_imputed, package = "DALEX")

head(titanic_imputed)
```


```{r}
library(xgboost)
library(EIX)
```

Fit a xgboost to the titanic imputed data.

```{r}
library("Matrix")
X <- sparse.model.matrix(survived ~ . - 1,  data = titanic_imputed)


xgb_model <- xgboost(X, titanic_imputed$survived, nrounds = 10, params = list(objective = "binary:logistic"), prediction = TRUE)
```

# Model parts

## Interaction measure


```{r}
interactions <- interactions(xgb_model, X, option = "interactions")
plot(interactions)
```
## Variable Importance

```{r} 
importance <- importance(xgb_model, X, option = "both")
plot(importance)
```


# Predict parts

## Interaction based explanation of single observation

```{r}
new_observation <- X[27,]
wf <- waterfall(xgb_model, new_observation, titanic_imputed[27,], option = "interactions")
plot(wf)
```

# Model diagnostics

```{r}
lolli <- lollipop(xgb_model, X)
plot(lolli, threshold=0.02)
```
