---
title: "fastshap"
author: "Szymon Maksymiuk"
date: "04 08 2020"
output:
  html_document:
    toc: true
    toc_float: true
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```



Load [`titanic_imputed`](https://modeloriented.github.io/DALEX/reference/titanic.html) data set.

```{r}
data(titanic_imputed, package = "DALEX")

head(titanic_imputed)
```

```{r}
library(fastshap)
```


Fit a forest type model to the titanic imputed data.

```{r}
ranger_model <- ranger::ranger(survived~., data = titanic_imputed, classification = TRUE, probability = TRUE)
```

# Model Parts

## Shapley based feature importance


```{r}
pred_fun <- function(X.model, newdata) {
  predict(X.model, newdata)$predictions[,2]
}

shap <- explain(ranger_model, X = titanic_imputed, pred_wrapper = pred_fun, nsim = 50)
library(ggplot2)
autoplot(shap)
```

# Model Profile

## shap based dependence plot

```{r}
pred_fun <- function(X.model, newdata) {
  predict(X.model, newdata)$predictions[,2]
}

shap <- explain(ranger_model, X = titanic_imputed, pred_wrapper = pred_fun, nsim = 50)
library(ggplot2)
autoplot(shap, type = "dependence", feature = "fare", X = titanic_imputed, smooth = TRUE)
```



# Predict Parts

## shap based contributions

### R plots

```{r}
pred_fun <- function(X.model, newdata) {
  predict(X.model, newdata)$predictions[,2]
}

shap <- explain(ranger_model, X = titanic_imputed, pred_wrapper = pred_fun, nsim = 50)
library(ggplot2)
autoplot(shap, type = "contribution", row_num = 1)
```

### Python imported plots

```{r}
pred_fun <- function(X.model, newdata) {
  predict(X.model, newdata)$predictions[,2]
}

shap <- explain(ranger_model, X = titanic_imputed, pred_wrapper = pred_fun, nsim = 50)

force_plot(shap[1,], baseline = mean(pred_fun(ranger_model, titanic_imputed)), feature_values = titanic_imputed[1,], display = "html")
```



