---
title: "iBreakDown"
date: "`r format(Sys.time(), '%d-%m-%Y')`"
output:
  html_document:
    toc: true
    toc_float: true
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```



Load [`titanic_imputed`](https://modeloriented.github.io/DALEX/reference/titanic.html) data set.

```{r}
data(titanic_imputed, package = "DALEX")

head(titanic_imputed)
```

```{r}
library(iBreakDown)
```


Fit a forest type model to the titanic imputed data.

```{r}
ranger_model <- ranger::ranger(survived~., data = titanic_imputed, classification = TRUE, probability = TRUE)
```

# Predict Parts

## Break Down additive


```{r}
library("iBreakDown")

custom_predict <- function(X.model, new_data) {
  predict(X.model, new_data)$predictions[,2]
}

bd <- break_down(ranger_model, new_observation = titanic_imputed[1,-8], data = titanic_imputed, predict_function = custom_predict)
plot(bd)
```

## Break Down interactions


```{r}
library("iBreakDown")

custom_predict <- function(X.model, new_data) {
  predict(X.model, new_data)$predictions[,2]
}

bd <- break_down(ranger_model, new_observation = titanic_imputed[1,-8], data = titanic_imputed, predict_function = custom_predict, interactions = TRUE)
plot(bd)
```


## shap


```{r}
library("iBreakDown")

custom_predict <- function(X.model, new_data) {
  predict(X.model, new_data)$predictions[,2]
}

bd <- shap(ranger_model, new_observation = titanic_imputed[1,-8], data = titanic_imputed, predict_function = custom_predict)
plot(bd)
```






