---
title: "iml"
date: "`r format(Sys.time(), '%d-%m-%Y')`"
output:
  html_document:
    toc: true
    toc_float: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```



Load [`titanic_imputed`](https://modeloriented.github.io/DALEX/reference/titanic.html) data set.

```{r}
data(titanic_imputed, package = "DALEX")

head(titanic_imputed)
```


```{r}
library(iml)
library(randomForest)
library(ggplot2)

set.seed(123)
```

Fit a random forest to the titanic imputed data.

```{r}
rf_model <- ranger::ranger(survived~., data = titanic_imputed, classification = TRUE, probability = TRUE)
```

```{r}
X <- titanic_imputed[which(names(titanic_imputed) != "survived")]
```

# Model parts

## Variable importance

```{r}
pred_fun <- function(X.model, newdata) {
  predict(X.model, newdata)$predictions[,2]
}
predictor <- Predictor$new(rf_model, data = X, y = titanic_imputed$survived, predict.function = pred_fun)
imp <- FeatureImp$new(predictor, loss = "logLoss")
plot(imp)
imp$results
```


## Interaction measure


```{r}
pred_fun <- function(X.model, newdata) {
  predict(X.model, newdata)$predictions[,2]
}
predictor <- Predictor$new(rf_model, data = X, y = titanic_imputed$survived, predict.function = pred_fun)
interact <- Interaction$new(predictor)
plot(interact)
```


## 2-way interaction measure

```{r}
pred_fun <- function(X.model, newdata) {
  predict(X.model, newdata)$predictions[,2]
}
predictor <- Predictor$new(rf_model, data = X, y = titanic_imputed$survived, predict.function = pred_fun)
interact <- Interaction$new(predictor, feature = "age")
plot(interact)
```


# Model profile

## PDP

```{r}
pred_fun <- function(X.model, newdata) {
  predict(X.model, newdata)$predictions[,2]
}
predictor <- Predictor$new(rf_model, data = X, y = titanic_imputed$survived, predict.function = pred_fun)
ale <- FeatureEffect$new(predictor, feature = "fare", method = "pdp")
plot(ale)
```

## ALE

```{r}
pred_fun <- function(X.model, newdata) {
  predict(X.model, newdata)$predictions[,2]
}
predictor <- Predictor$new(rf_model, data = X, y = titanic_imputed$survived, predict.function = pred_fun)
ale <- FeatureEffect$new(predictor, feature = "fare")
plot(ale)
```


## Surrogate for the whole model

```{r}
pred_fun <- function(X.model, newdata) {
  predict(X.model, newdata)$predictions[,2]
}
predictor <- Predictor$new(rf_model, data = X, y = titanic_imputed$survived, predict.function = pred_fun)
tree <- TreeSurrogate$new(predictor, maxdepth = 2)
plot(tree)
```



# Predict parts

## LIME


```{r}
pred_fun <- function(X.model, newdata) {
  predict(X.model, newdata)$predictions[,2]
}
predictor <- Predictor$new(rf_model, data = X, y = titanic_imputed$survived, predict.function = pred_fun)
lime <- LocalModel$new(predictor, x.interest = X[1, ])
plot(lime)
lime$results
```




## SHAP


```{r}
pred_fun <- function(X.model, newdata) {
  predict(X.model, newdata)$predictions[,2]
}
predictor <- Predictor$new(rf_model, data = X, y = titanic_imputed$survived, predict.function = pred_fun)
shapley <- Shapley$new(predictor, x.interest = X[1, ], sample.size = 50)
plot(shapley)
```

# Predict profile

## ICE curves

```{r}
pred_fun <- function(X.model, newdata) {
  predict(X.model, newdata)$predictions[,2]
}
predictor <- Predictor$new(rf_model, data = X, y = titanic_imputed$survived, predict.function = pred_fun)
ice <- FeatureEffect$new(predictor, feature = "fare", method = "ice")
plot(ice)
```