---
title: "lime"
date: "`r format(Sys.time(), '%d-%m-%Y')`"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```



Load [`titanic_imputed`](https://modeloriented.github.io/DALEX/reference/titanic.html) data set.

```{r}
data(titanic_imputed, package = "DALEX")

head(titanic_imputed)
```


```{r}
library(lime)
library(randomForest)
library(MASS)

set.seed(123)
```

Fit LDA to the titanic imputed data.

```{r}
lda_model <- lda(survived~., data = titanic_imputed)
```



# Predict parts

## LIME



```{r}
lda_lime <- lime::lime(titanic_imputed, lda_model)
predict_model.randomForest <- function(x, newdata, type = "prob"){
  as.data.frame(predict(x, newdata = newdata))
}
explanations <- lime::explain(titanic_imputed[1:4,], lda_lime, n_labels = 1, n_features = 5)

plot_features(explanations)
```

```{r}
lda_lime <- lime::lime(titanic_imputed, lda_model)
predict_model.randomForest <- function(x, newdata, type = "prob"){
  as.data.frame(predict(x, newdata = newdata))
}
explanations <- lime::explain(titanic_imputed[1:4,], lda_lime, n_labels = 1, n_features = 5)

plot_explanations(explanations)
```


