---
title: "live"
date: "`r format(Sys.time(), '%d-%m-%Y')`"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

Load [`titanic_imputed`](https://modeloriented.github.io/DALEX/reference/titanic.html) data set.

```{r}
data(titanic_imputed, package = "DALEX")

head(titanic_imputed)
```


```{r}
library(live)

set.seed(123)
```

Fit a random forest to the titanic imputed data.

```{r}
rf_model <- ranger::ranger(survived~., data = titanic_imputed, classification = TRUE, probability = TRUE)
```





# Predict parts

## LIVE explanation


```{r}
similar <- sample_locally(data = titanic_imputed,
                          explained_instance = titanic_imputed[1, ],
                          explained_var = "survived",
                          size = 500)

pred_fun <- function(X.model, newdata) {
  predict(X.model, newdata)$predictions[,2]
}
similar1 <- add_predictions(to_explain = similar,
                            black_box_model = rf_model,
                            predict_fun = pred_fun)
explanation <- fit_explanation(live_object = similar1,
                             white_box = "regr.lm")
plot(explanation, type = "forest")
```




```{r}
similar <- sample_locally(data = titanic_imputed,
                          explained_instance = titanic_imputed[1, ],
                          explained_var = "survived",
                          size = 500)
pred_fun <- function(X.model, newdata) {
  predict(X.model, newdata)$predictions[,2]
}
similar1 <- add_predictions(to_explain = similar,
                            black_box_model = rf_model,
                            predict_fun = pred_fun)
explanation <- fit_explanation(live_object = similar1,
                             white_box = "regr.lm")

plot(explanation, type = "waterfall")
```


