---
title: "pdp"
date: "`r format(Sys.time(), '%d-%m-%Y')`"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```



Load [`titanic_imputed`](https://modeloriented.github.io/DALEX/reference/titanic.html) data set.

```{r}
data(titanic_imputed, package = "DALEX")

head(titanic_imputed)
```


```{r}
library(pdp)
library(ggplot2)
library(randomForest)

set.seed(123)
```

Fit a random forest to the titanic imputed data.

```{r}
rf_model <- randomForest(factor(survived)~., data = titanic_imputed)
```



# Model parts

## Variable importance

Extract the most important predictors.

```{r}
topPredictors(rf_model, n = 3)
```



# Model profile

## PDP with ICE curves.

```{r}
pred_fun <- function(object, newdata) predict(object, newdata, type = "prob")[,2]
rf_pdp <- partial(rf_model, pred.var = c("fare"), ice = TRUE, pred.fun = pred_fun )
plotPartial(rf_pdp)
```

PDP for two variables 
```{r}
pred_fun <- function(object, newdata) predict(object, newdata, type = "prob")[,2]
rf_pdp <- partial(rf_model, pred.var = c("fare", "age"), pred.fun = pred_fun)
plotPartial(rf_pdp)
```

Use `autoplot` function to produce PDP with `ggplot2`.

```{r}
pred_fun <- function(object, newdata) predict(object, newdata, type = "prob")[,2]
rf_pdp <- partial(rf_model, pred.var = c("fare"), ice = TRUE, pred.fun = pred_fun)
autoplot(rf_pdp)
```




