---
title: "shapper"
date: "`r format(Sys.time(), '%d-%m-%Y')`"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

Load [`titanic_imputed`](https://modeloriented.github.io/DALEX/reference/titanic.html) data set.

```{r}
data(titanic_imputed, package = "DALEX")

head(titanic_imputed)
```


```{r}
library(DALEX)
library(shapper)
library(randomForest)

set.seed(123)
```

Fit a random forest and logistic regression to the titanic imputed data.

```{r}
rf_model <- ranger::ranger(survived~., data = titanic_imputed, classification = TRUE, probability = TRUE)
glm_model <- glm(survived~., data = titanic_imputed)
```



# Predict Parts

## SHAP 


```{r}
pred_fun <- function(X.model, newdata) {
  predict(X.model, newdata)$predictions[,2]
}
ive_rf <- individual_variable_effect(rf_model, 
                                     predict_function = pred_fun,
                                     data = titanic_imputed[,-8],
                                     new_observation = titanic_imputed[1, -8],
                                     nsamples = 50)

plot(ive_rf)
```

Multiple models on one plot


```{r}
pred_fun <- function(X.model, newdata) {
  predict(X.model, newdata)$predictions[,2]
}
ive_rf <- individual_variable_effect(rf_model, data = titanic_imputed[,-8],
                                     predict_function = pred_fun,
                                     new_observation = titanic_imputed[1, -8],
                                     nsamples = 50)
ive_glm <- individual_variable_effect(glm_model, data = titanic_imputed[,-8],
                                     new_observation = titanic_imputed[1, -8],
                                     nsamples = 50)

plot(ive_rf, ive_glm)
```

