---
title: "vip"
author: "Alicja Gosiewska"
date: "17 08 2020"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

Load [`titanic_imputed`](https://modeloriented.github.io/DALEX/reference/titanic.html) data set.

```{r}
data(titanic_imputed, package = "DALEX")

head(titanic_imputed)
```


```{r}
library(vip)
library(randomForest)

set.seed(123)
```

Fit a random forest and logistic regression to the titanic imputed data.

```{r}
rf_model <- randomForest(survived~., data = titanic_imputed)
glm_model <- glm(survived~., data = titanic_imputed)
```

# Model parts

## Variance-based Variable Importance

```{r}
vip(object = rf_model, method = "firm")
```

## Model-specific Variable Importance

```{r}
vip(object = rf_model, method = "model")
```


## Permutation-based Variable Importance

```{r}
pred_fun = function(object, newdata) predict(object, newdata)
vip(object = rf_model, method = "permute", target = "survived", metric = "auc", pred_wrapper = pred_fun, reference_class = 1)
```


## Shapley-based Variable Importance

```{r}
pred_fun = function(object, newdata) predict(object, newdata)
vip(object = rf_model, method = "shap", pred_wrapper = pred_fun)
```


## Interaction strength for pairs of features

```{r}
vint(rf_model, feature_names = c("age", "fare"))
```

